version: '3.6'

services:
  async-download-service:

    build: .
    ports:
      - "8080:8080"
    working_dir: /app
    volumes:
      - ./test_photos:/photos
    env_file:
      - .env
    command:
      python server.py --enable_logging
